{
  "timestamp": "20250831_105308",
  "dockerfile_path": "envgym/envgym.dockerfile",
  "image_name": "envgym_test_1756637587",
  "build": {
    "success": false,
    "stdout": "",
    "stderr": "#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from envgym.dockerfile\n#1 transferring dockerfile: 1.35kB done\n#1 DONE 0.0s\n\n#2 resolve image config for docker-image://docker.io/docker/dockerfile:1.4\n#2 DONE 0.1s\n\n#3 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc\n#3 CACHED\n\n#4 [internal] load .dockerignore\n#4 transferring context: 2B done\n#4 DONE 0.0s\n\n#5 [internal] load metadata for docker.io/continuumio/miniconda3:4.7.12\n#5 DONE 0.2s\n\n#6 [stage-0  1/11] FROM docker.io/continuumio/miniconda3:4.7.12@sha256:6c979670684d970f8ba934bf9b7bf42e77c30a22eb96af1f30a039b484719159\n#6 DONE 0.0s\n\n#7 [stage-0  4/11] RUN --mount=type=cache,target=/var/cache/apt     apt-get update &&     apt-get install -y wget unzip &&     rm -rf /var/lib/apt/lists/*\n#7 CACHED\n\n#8 [stage-0  2/11] WORKDIR /app\n#8 CACHED\n\n#9 [stage-0  3/11] RUN echo \"deb http://archive.debian.org/debian buster main\" > /etc/apt/sources.list     && echo \"deb http://archive.debian.org/debian-security buster/updates main\" >> /etc/apt/sources.list\n#9 CACHED\n\n#10 [stage-0  5/11] RUN mkdir -p plots models results csvs\n#10 CACHED\n\n#11 [internal] load build context\n#11 transferring context: 311B done\n#11 DONE 0.0s\n\n#12 [stage-0  6/11] RUN wget -O dataset.zip \"https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\n#12 0.224 --2025-08-31 10:53:07--  https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\n#12 0.234 Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.43.25, 188.185.48.194, ...\n#12 0.459 Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.\n#12 0.779 HTTP request sent, awaiting response... 301 MOVED PERMANENTLY\n#12 0.913 Location: /records/6388301/files/sixthsense-dataset-v2.0.zip [following]\n#12 0.913 --2025-08-31 10:53:08--  https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\n#12 0.914 Reusing existing connection to zenodo.org:443.\n#12 0.914 HTTP request sent, awaiting response... 404 NOT FOUND\n#12 1.041 2025-08-31 10:53:08 ERROR 404: NOT FOUND.\n#12 1.041 \n#12 ERROR: process \"/bin/sh -c wget -O dataset.zip \\\"https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\\\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\" did not complete successfully: exit code: 8\n------\n > [stage-0  6/11] RUN wget -O dataset.zip \"https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip:\n0.224 --2025-08-31 10:53:07--  https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\nconnected.\n301 MOVED PERMANENTLY\n0.913 Location: /records/6388301/files/sixthsense-dataset-v2.0.zip [following]\n0.913 --2025-08-31 10:53:08--  https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\n0.914 Reusing existing connection to zenodo.org:443.\n0.914 HTTP request sent, awaiting response... 404 NOT FOUND\n1.041 2025-08-31 10:53:08 ERROR 404: NOT FOUND.\n1.041 \n------\nERROR: failed to solve: process \"/bin/sh -c wget -O dataset.zip \\\"https://zenodo.org/record/6388301/files/sixthsense-dataset-v2.0.zip?download=1\\\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\" did not complete successfully: exit code: 8\n"
  },
  "run": {
    "success": false,
    "stdout": "",
    "stderr": ""
  }
}